### ISSUE TITLE
404 for spell checker

### ISSUE THREAD

**Issue by bearcatsandor** [iamcco/coc-spell-checker#10]
When I start up vim, I get the following error message:

[coc.nvim] Error on install coc-spellchecker: Error: Invalid response from https://registry.npmjs.org/coc-spellchecker: 404

Is this module pointing at the right place, or is the site just down temporarily?

**Comment by iamcco** [comment]
coc-spell-checker

**Comment by bearcatsandor** [comment]
Arrgh. Thank you! That's what I get for installing coc after a 3 hour math test.
