### ISSUE TITLE
Feature: Exclude import statements

### ISSUE THREAD

**Issue by esetnik** [iamcco/coc-spell-checker#14]
I think it would be a logical default to exclude import statements. Many packages are not real words. Is there an easy way to achieve this? Happy to submit a PR too.

Example:

![image](https://user-images.githubusercontent.com/664434/81943751-c5ef9780-95c9-11ea-8fd1-4b501242bfe1.png)

**Comment by iamcco** [comment]
checkout out https://github.com/iamcco/coc-spell-checker/blob/master/package.json#L331
