### ISSUE TITLE
cSpell.addWordToDictionary not works

### ISSUE THREAD

**Issue by xaljer** [iamcco/coc-spell-checker#22]
**Describe the bug**
`nnoremap <Leader>ca :<C-U>CocCommand cSpell.addWordToDictionary<CR>` not works since update coc to 79 version.

![image](https://user-images.githubusercontent.com/8309631/96021694-605a4c80-0e82-11eb-9456-978c9dcd10f1.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 

Log:

```
```

**Comment by CallumHoward** [comment]
I am also looking for a mapping that can do this, and found the same error
