### ISSUE TITLE
Allow enable/disable through command line

### ISSUE THREAD

**Issue by Niklas81** [iamcco/coc-spell-checker#31]
Coc itself comes with the commands `CocEnable` and `CocDisable` to allow toggling it on and off.
I don't mind always having spell-checking enabled in e.g. markdown-files, but when enabling it in code files, it displays a lot of "spelling-errors" that aren't really errors.
To circumvent this, it would be really helpful if I could enable it by default in all supported files, but then be able to toggle it on and of with a simply command, rather than needing to contaminate my code base with comments for a text editor tool.
E.g. `:SpellOn` and `:SpellOff`.

Any chance we could get this? I'm sure a lot of people would like it!

**Comment by jdsutherland** [comment]
You can do this with `:CocCommand cSpell.toggleEnableSpellChecker`

**Comment by Niklas81** [comment]
Awesome, thanks!
