### ISSUE TITLE
Where does the words through "cSpell.addWordToDictionary" goes?

### ISSUE THREAD

**Issue by ywpkwon** [iamcco/coc-spell-checker#6]
Thanks for this plugin! While I'm enjoying this plugin, I got a question.

I'm aware of `coc-setting.json` or `cSpell.json`, and one can add words like `"cSpell.words": ["wword"],` or `"words": [ "wword" ]`, respectively. 

But when I did `:CocCommand cSpell.addWordToDictionary` for word `prototxt` for example, there was no update information in those files. (Yes, the word has no more warning so it works well). I'm just wondering: when I add words through `:CocCommand cSpell.addWordToDictionary`, where can I see those words?

FYI, I'm not having `cSpell.json` and just only having `coc-setting.json` in `~/.config/nvim`.

**Comment by iamcco** [comment]
Check your project workspace's `.vim/coc-setting.json`.
